networks:
  servarr_default:
    name: servarr_default
    ipam:
      config:
        - subnet: 172.39.0.0/24
        
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # sabnzbd
      - 9696:9696 # prowlarr
    networks:
      servarr_default:
        ipv4_address: 172.39.0.2
    volumes:
      - /etc/docker/servarr/gluetun:/config
    env_file:
      - .env
    environment:
      - DNS_ADDRESS=127.0.0.11
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/fallenbagel/jellyseerr:latest
    init: true
    ports:
      - 5055:5055
    networks:
      servarr_default:
        ipv4_address: 172.39.0.3
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/jellyseerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    
  
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    networks:
      servarr_default:
        ipv4_address: 172.39.0.4
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/radarr:/config
      - /data:/data
    restart: unless-stopped
    labels:
      - homepage.group=Media Management
      - homepage.name=Radarr
      - homepage.id=col-medium__radarr
      - homepage.icon=radarr
      - homepage.href=${RADARR_IP_URL}
      - homepage.weight=0
      - homepage.widget.type=radarr
      - homepage.widget.url=${RADARR_IP_URL}
      - homepage.widget.key=${RADARR_API_KEY}
    
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - "8989:8989"
    networks:
      servarr_default:
        ipv4_address: 172.39.0.5
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/sonarr:/config
      - /data:/data
    restart: unless-stopped
    labels:
      - homepage.group=Media Management
      - homepage.name=Sonarr
      - homepage.id=col-medium__sonarr
      - homepage.icon=sonarr
      - homepage.href=${SONARR_IP_URL}
      - homepage.weight=1
      - homepage.widget.type=sonarr
      - homepage.widget.url=${SONARR_IP_URL}
      - homepage.widget.key=${SONARR_API_KEY}
    
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    ports:
      - "8686:8686"
    networks:
      servarr_default:
        ipv4_address: 172.39.0.6
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/lidarr:/config
      - /data:/data
    restart: unless-stopped
    labels:
      - homepage.group=Media Management
      - homepage.name=Lidarr
      - homepage.id=col-medium__lidarr
      - homepage.icon=lidarr
      - homepage.href=${LIDARR_IP_URL}
      - homepage.weight=2
      - homepage.widget.type=lidarr
      - homepage.widget.url=${LIDARR_IP_URL}
      - homepage.widget.key=${LIDARR_API_KEY}
      
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - "6767:6767"
    networks:
      servarr_default:
        ipv4_address: 172.39.0.8
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/bazarr:/config
      - /data:/data
    restart: unless-stopped
    labels:
      - homepage.group=Media Management
      - homepage.name=Bazarr
      - homepage.id=col-medium__bazarr
      - homepage.icon=bazarr
      - homepage.href=${BAZARR_IP_URL}
      - homepage.weight=3
      - homepage.widget.type=bazarr
      - homepage.widget.url=${BAZARR_IP_URL}
      - homepage.widget.key=${BAZARR_API_KEY}

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    ports:
      - "6969:6969"
    networks:
      servarr_default:
        ipv4_address: 172.39.0.7
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/whisparr:/config
      - /data:/data
    restart: unless-stopped

  notifiarr:
    container_name: notifiarr
    image: golift/notifiarr
    ports:
      - "5454:5454"
    networks:
      servarr_default:
        ipv4_address: 172.39.0.9
    volumes:
      - /etc/docker/servarr/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    restart: unless-stopped

  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      servarr_default:
        ipv4_address: 172.39.0.10
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/syncthing:/config
      - /data:/data
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/prowlarr:/config
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/docker/servarr/sabnzbd:/config
      - /data:/data
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    restart: unless-stopped